name: commitlint

on: [pull_request]

permissions:
  contents: read

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: 18
          cache: npm

      - run: npm install -g @commitlint/cli @commitlint/config-conventional
      - run: 'echo "${PR_TITLE}" | commitlint'
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
